name: marine_aqua_technologies
description: Marine Aqua Technologies - Smart Aquaculture
publish_to: "none"

version: 1.0.0+57

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/mat_guide.pdf
    - lib/marine_6g.png
    - lib/marine_white_shield.png
    - lib/vibrio_shield.png
    - lib/protab.png
    - lib/volt-x.png
    - lib/volt-x.png
    - lib/oxytab.png
    - lib/bio_sludge_x.png
    - lib/free_moult.png
    - lib/red_thunder.png
    - lib/starmin.png
    - lib/white_shield.png
