name: marine_aqua_technologies
description: MARINE AQUA TECHNOLOGIES - Smart Aquaculture. Better Results.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - bio sludge -x.png
    - free moult.png
    - marine 6g.png
    - matine white shield.png
    - oxytab.png
    - protab.png
    - red thunder.png
    - starmin.png
    - vibrio shield.png
    - volt-x.png
    - white shield.png
