name: marine_aqua_technologies
description: Marine Aqua Technologies - Smart Aquaculture
publish_to: "none"

version: 1.0.0+57

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mat_guide.pdf
    - assets/marine_logo.png
    - assets/marine_6g.png
    - assets/marine_white_shield.png
    - assets/vibrio_shield.png
    - assets/protab.png
    - assets/volt-x.png
    - assets/oxytab.png
    - assets/bio_sludge_x.png
    - assets/free_moult.png
    - assets/red_thunder.png
    - assets/starmin.png
